name: Run TF policy test
on:
  workflow_dispatch:

jobs:
  terraform:
    permissions: write-all
#      contents: read # for actions/checkout to fetch code
#      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
#      actions: read  
    runs-on: ubuntu-latest
    name: Run TF plan
    steps:
    - run: |
        jq --version      
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    - name: Terraform Plan
      id: plan
      run: | 
        terraform init
        terraform plan -out=tfplan.bin
        terraform show -json tfplan.bin > tfplan.json        
      working-directory: terraform

    - name: Install checkov
      run: |
        pip3 install checkov
        # check checkov is installed
        if [[ $(pip3 list | grep -i "checkov") =~ "checkov" ]]; then
          echo "checkov is installed"
        else
          echo "checkov is not installed"
          echo "Install checkov."
          exit 1
        fi        
      
    - name: Terraform policy validation
      run: |
        ls -a 
        checkov \
          -f tfplan.json --external-checks-dir checkov/policies \
          -c CUSTOM_TAGS_POLICY --skip-check '*_AWS_*' --soft-fail -o sarif > reports/results.sarif
    
